### ISSUE TITLE
如果去掉RocksDB就好了，保持纯粹，部署简单 多好

### ISSUE THREAD

**Issue by zhuxiujia** [quasipaa/Physeter#1]
如果去掉RocksDB就好了，保持纯粹，部署简单 多好

**Comment by quasipaa** [comment]
> 如果去掉RocksDB就好了，保持纯粹，部署简单多好
RocksDB是嵌入式的，这个没有影响，而且前期我也是自己尝试做过索引，但是工作量很大，而且性能还不好，直接拿开源成熟的嵌入式KV引擎是个好的选择
